#!/usr/bin/env python

import sys
import json
from datetime import datetime


def print_time(timestamps):
    output = {}
    for ts in timestamps:
        dashes = datetime.fromtimestamp(int(ts)).strftime('%Y-%m-%d %H:%M:%S')
        slashes = datetime.fromtimestamp(int(ts)).strftime('%d/%m/%Y %H:%M:%S')
        local = datetime.fromtimestamp(int(ts)).strftime('%c')
        tsdict = {ts: [local, slashes, dashes]}
        output.update(tsdict)
    print(json.dumps(output, indent=4))


if __name__ == '__main__':

    print_time(sys.argv[1:])
